In [1]:
import numpy as np

In [4]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [5]:
myarr= np.array(myList)

In [6]:
type(myarr)

numpy.ndarray

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.arange(0,6,3)

array([0, 3])

In [8]:
np.linspace(0,6,4,endpoint=False)

array([0. , 1.5, 3. , 4.5])

In [15]:
np.random.rand(2,3)

array([[0.27380345, 0.5091628 , 0.68372498],
       [0.23725877, 0.25578462, 0.91141813]])

In [13]:
np.random.randn(2,3)

array([[ 0.51001811,  0.57916225, -0.2582705 ],
       [ 0.69887295,  1.37855752, -0.29443931]])

In [19]:
np.random.randint(0,5,2)
#np.random.randint(0,5,(2,2))

array([0, 4])

In [20]:
np.random.seed(101)
np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])

In [21]:
ranarr=np.random.randint(0,101,2)

In [17]:
ranarr

array([28,  7])

In [18]:
ranarr.dtype

dtype('int32')

In [20]:
myarray=np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

# Slice & Copy

In [25]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_slice = arr[0:5]
arr_slice

array([0, 1, 2, 3, 4])

In [27]:
arr_slice[:]=99
arr_slice

array([99, 99, 99, 99, 99])

In [29]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_copy=arr.copy()

In [32]:
arr_copy[:]=99
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2d slice

In [36]:
arr_2d = np.array([[5,2,4],[3,4,2],[6,7,8]])
arr_2d

array([[5, 2, 4],
       [3, 4, 2],
       [6, 7, 8]])

In [42]:
arr_2d[1,1]
#arr_2d[1][1]

4

In [43]:
arr_2d[:2,1:]

array([[2, 4],
       [4, 2]])

# Conditional selection

In [48]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_arr = arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [52]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
import numpy as np
dice_rolls=np.array([1,5,3,2,6,4,1,2,3,4,5,6,3,2,1,5,2,6,4,6,3,1])
total_rolls_over_two=len(dice_rolls[dice_rolls>2])
total_rolls_over_two

14

# Numpy operations

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr / arr
#warning not error

C:\Users\gunne\AppData\Local\Temp/ipykernel_1204/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
1/arr
#warning not full error

C:\Users\gunne\AppData\Local\Temp/ipykernel_1204/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [51]:
arr/0
#warning not full error

C:\Users\gunne\AppData\Local\Temp/ipykernel_1204/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\gunne\AppData\Local\Temp/ipykernel_1204/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [52]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [55]:
np.log(arr)
#warning not full error

C:\Users\gunne\AppData\Local\Temp/ipykernel_1204/4270500163.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Summary statistics

In [13]:
arr2d = np.arange(0,25).reshape(5,5)

In [24]:
arr2d.shape

(5, 5)

In [17]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr2d.sum()

300

In [26]:
# arr2d.shape >>>> (5,5)
#                  0    1
#                rows   columns

arr2d.sum(axis=0)
# sum ACROSS the rows = columns

array([50, 55, 60, 65, 70])

In [23]:
arr2d.sum(axis=1)
# sum ACROSS columns = rows

array([ 10,  35,  60,  85, 110])

In [28]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total = np.sum(account_transactions)
account_total

2720